### ISSUE TITLE
Ability to use colon in element tag

### ISSUE THREAD

**Issue by cwiese** [GenieFramework/StippleUI.jl#35]
I am using the quasar drawer :
```
      <q-drawer
        v-model="drawer"
        show-if-above
        :width="200"
        :breakpoint="500"
      >
```

trying to get quasar_pure to produce this output ,,but a name attribute cannot have colon
```
 quasar_pure(:tabs, ":breakpoint" = 500, args...; kwargs...)
```

**Comment by hhaensel** [comment]
```julia
quasar_pure(:drawer, "this goes between the brackets", :show__if__above, fieldname=:drawer, width=@data("200"), breakpoint=@data("500"))
```
Note that the first positional argument goes between the brackets, so you have to place the inner part before the `:show__if__above`. The `@data` provides the colons to the keyword argument. You could also have integer or array arguments to `@data`, if quasar syntax would need it.
Final note: If you want to have the parameters before the inner arguments, there are two ways of achieving it.
1. Don't use keyword arguments, e.g. `show__if__above = true` instead of `:show__if__above`
`quasar_pure(:drawer, show__if__above=true, fieldname=:drawer, width=@data("200"), breakpoint=@data("500"), "this goes between the brackets")`. In this case you cannot use arguments like `@click(:button)`.
2. Provide an empty string as first positional argument (not counting the symbol `drawer`) and provide the inner part with the keyword "inner")
`quasar_pure(:drawer, "", :show__if__above, fieldname=:drawer, width=@data("200"), breakpoint=@data("500"), inner="this also goes between the brackets")`

**Comment by essenciary** [comment]
We already have a Drawer component, does that not work as expected? https://github.com/GenieFramework/StippleUI.jl/blob/master/src/Drawers.jl

**Comment by hhaensel** [comment]
In the version I was currently working at, it was not exported and it resided under `Drawer.jl`, seems as if it was refactored lately 😉 
So please use `drawer(` instead of `quasar_pure(:drawer, `. All the rest about the API remains valid, of course.

**Comment by cwiese** [comment]
Yeah I do not understand using StiippleUI#v.0.9.0

I see the export of drawer but 

```
using StippleUI: drawer
ERROR: UndefVarError: drawer not defined
```

**Comment by hhaensel** [comment]
The reason is that we forgot to reexport in StippleUI. For the time being you can do
`import StippleUI.Drawers.drawer`

**Comment by essenciary** [comment]
Thanks - I've patched the code to export and will come up in the next release.
