### ISSUE TITLE
add q-list

### ISSUE THREAD

**Issue by alerem18** [GenieFramework/StippleUI.jl#96]
quasar component q-list is not supported

**Comment by hhaensel** [comment]
That's not quite right, there are `list()`, `ìtemsection()` and `item()`. in most of the times you can simply omit the `q-` at the beginning of the html-element name to obtain the respective julia command.
There is also the possibility of using `parse_vue_html()` in many cases, but that currently fails for `q-list`. That will be fixed in the next release.
